crypto:
  private_key_file: './private_key.pem'
  public_key_file: './public_key.pem'
  direct_crypt_limit: 200 #Max number of bytes for direct encryption instead of hybrid encryption

mqtt:
  local:
    address: '192.168.0.5'
    port: 1883
    user: 'mqtt'
    password: 'qrpposl1292'
    client_id: 'mqtt_cryptbridge_{random_int}'
    topic_outbound: 'cryptbridge/out/#'
    topic_inbound: 'cryptbridge/in/#'

  global:
    address: 'test.mosquitto.org'
    port: 1883
    user: '{$GLOBAL_MQTT_USERNAME}' # Optional, only used in case of auth failure at first attempt
    password: '{$GLOBAL_MQTT_PASSWORD}'
    client_id: '{random_int}' # Optional, uses random string if not provided
    topic: '{random_int}' # o
    retain: False


